### ISSUE TITLE
Don't use this software.

### ISSUE THREAD

**Issue by jamesdev01** [virtualmin/virtualmin-nginx#38]
Nevermind, it's junk. 

Stay away from this software, and don't bother contributing. I wasted hours building a beautiful readme file with full instructions on how to get this installed, all for nothing. I ended up deleting my fork after enough berating by the unprofessional devs.

The devs are thickheaded, insult contributors, and are living in 1999, refusing to come into the 21st century. The interface is outdated, and not functional with modern technologies. Devs believe they know everything but yet they haven't learned anything newer than the dotcom boom. 

They refuse to do anything to improve the software, and won't even take free contributions from experts because they are luddites. Do not waste your time with this software.

**Comment by iliajie** [comment]
Hello,

Preferably, from the start you should install it as a LEMP stack, using `virtualmin-install.sh --bundle LEMP` command.

**Comment by jamesdev01** [comment]
Ah yes, as I did install that first already though. I will update the readme file I prosposed with those details.

**Comment by jamesdev01** [comment]
I updated my readme file again and this time it is complete.

**Comment by jamesdev01** [comment]
Let me know what you thikn about my readme file, and I hope this helps users get this installed as well as encourage additional contributions.

**Comment by iliajie** [comment]
James,

> I wasted hours building a beautiful readme file

Your `README.md` indeed was beautiful. But it wasn't correct unfortunately.

> Stay away from this software, and don't bother contributing.

Look, things may happen not as you expect or see them to happen. You shouldn't let your emotions to take over.

> The devs are thickheaded, insult contributors, and are living in 1999, refusing to come into the 21st century. 

Is `README.md` in Virtualmin or Webmin repos are also from 1999? Come on! Don't be angry please. But again your contribution to `README.md` for `Virtualmin-Nginx` plugin was not correct. It is beautiful, yes, and I like the badges, and we will look into adding them to our main Webmin and Virtualmin repos in the near future. But plugin is a plugin.

Besides, `Virtualmin-Nginx` plugin is special out of all. Because it requires various of other configurations made to work properly, and we make it all with `virtualmin-install.sh -b LEMP` script. You or any other user (even advanced one) won't be able to get it all right in a timely manner with your instructions. This is why it's all automated.

You provided `README.md` that made it look that `Virtualmin-Nginx` plugin is a separate product which ~can~ _should_ be easily installed into existing Virtualmin box manually to work. Well, this is not correct. The only best recommendation to install it is using `virtualmin-install.sh -b LEMP` option. Not manually.

Also, `Virtualmin-Nginx` plugin has nothing to do with Nginx reverse proxy!

Besides, PHP is installed automatically by the Virtualmin install script. If one was suggesting this, it means something went off pretty badly.

No offence, we need contributions but please don't expect that we would be able to merge anything that is suggested in a PR. We cannot do this, as we have responsibility in front of our users.

**Comment by iliajie** [comment]
And please, stop changing titles. A title should reflect not how you feel at the moment but the problem being discussed and solved.
